// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 3YRsZHmU6M2Qk7WYDM9QQ4

import * as React from "react";
import { hasVariant, ensureGlobalVariants } from "@plasmicapp/react-web";
import { Web3GlobalContext } from "@plasmicpkgs/nft-builder";

export interface GlobalContextsProviderProps {
  children?: React.ReactElement;
  web3GlobalContextProps?: Partial<
    Omit<React.ComponentProps<typeof Web3GlobalContext>, "children">
  >;
}

export default function GlobalContextsProvider(
  props: GlobalContextsProviderProps
) {
  const { children, web3GlobalContextProps } = props;

  return (
    <Web3GlobalContext
      {...web3GlobalContextProps}
      apiUrl={
        web3GlobalContextProps && "apiUrl" in web3GlobalContextProps
          ? web3GlobalContextProps.apiUrl!
          : undefined
      }
      contractPackageId={
        web3GlobalContextProps && "contractPackageId" in web3GlobalContextProps
          ? web3GlobalContextProps.contractPackageId!
          : "0x8372201a47f77c209c4d56bfae19fae5c1120cc723eca5670ff42f7f569a4677"
      }
      importedCollection={
        web3GlobalContextProps && "importedCollection" in web3GlobalContextProps
          ? web3GlobalContextProps.importedCollection!
          : undefined
      }
    >
      {children}
    </Web3GlobalContext>
  );
}
