// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: wK4ai2Pky86oQbuEBAzKHv
// Component: 30k4YlhlpLD_

import * as React from "react";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import Header from "../../Header"; // plasmic-import: kHpfvMoPjbW5/component
import { ConnectWalletButton } from "@plasmicpkgs/nft-builder";
import { Tabs } from "@plasmicpkgs/antd/skinny/registerTabs";
import { TabPane } from "@plasmicpkgs/antd/skinny/registerTabs";
import { AntdSteps } from "@plasmicpkgs/antd5/skinny/registerSteps";

import { useScreenVariants as useScreenVariantszDoh8C8VtaK } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: zDoh8-c8vtaK/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: 66MC2d9B7YecVEphuUMtqF/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: wK4ai2Pky86oQbuEBAzKHv/projectcss
import sty from "./PlasmicConnectWalletViewMintingNftDetails.module.css"; // plasmic-import: 30k4YlhlpLD_/css

createPlasmicElementProxy;

export type PlasmicConnectWalletViewMintingNftDetails__VariantMembers = {};
export type PlasmicConnectWalletViewMintingNftDetails__VariantsArgs = {};
type VariantPropType =
  keyof PlasmicConnectWalletViewMintingNftDetails__VariantsArgs;
export const PlasmicConnectWalletViewMintingNftDetails__VariantProps =
  new Array<VariantPropType>();

export type PlasmicConnectWalletViewMintingNftDetails__ArgsType = {};
type ArgPropType = keyof PlasmicConnectWalletViewMintingNftDetails__ArgsType;
export const PlasmicConnectWalletViewMintingNftDetails__ArgProps =
  new Array<ArgPropType>();

export type PlasmicConnectWalletViewMintingNftDetails__OverridesType = {
  root?: Flex__<"div">;
  connectWalletButton?: Flex__<typeof ConnectWalletButton>;
  antdTabs?: Flex__<typeof Tabs>;
  steps?: Flex__<typeof AntdSteps>;
  antdTabs2?: Flex__<typeof Tabs>;
  steps2?: Flex__<typeof AntdSteps>;
};

export interface DefaultConnectWalletViewMintingNftDetailsProps {
  className?: string;
}

const $$ = {};

function PlasmicConnectWalletViewMintingNftDetails__RenderFunc(props: {
  variants: PlasmicConnectWalletViewMintingNftDetails__VariantsArgs;
  args: PlasmicConnectWalletViewMintingNftDetails__ArgsType;
  overrides: PlasmicConnectWalletViewMintingNftDetails__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "antdTabs.activeKey",
        type: "private",
        variableType: "array",
        initFunc: ({ $props, $state, $queries, $ctx }) =>
          hasVariant(globalVariants, "screen", "tabletSmall") ? "1" : "1"
      },
      {
        path: "steps.current",
        type: "private",
        variableType: "number",
        initFunc: ({ $props, $state, $queries, $ctx }) => 1
      },
      {
        path: "antdTabs2.activeKey",
        type: "private",
        variableType: "array",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined
      },
      {
        path: "steps2.current",
        type: "private",
        variableType: "number",
        initFunc: ({ $props, $state, $queries, $ctx }) => 1
      },
      {
        path: "teamMembers",
        type: "private",
        variableType: "array",
        initFunc: ({ $props, $state, $queries, $ctx }) => [
          {
            name: "james",
            role: "Co Founder",
            image:
              "https://s3-alpha-sig.figma.com/img/21c1/c284/eddacccb4e22ee7d2abea1058a784bf2?Expires=1745193600&Key-Pair-Id=APKAQ4GOSFWCW27IBOMQ&Signature=gCneODEcNL1rKq3gWwUkRGlMlkJiFOW-TSt3US569UZ3P2lun0RdhKinihk9KoYX7OFOXMaHGpH-NcFt6CbRZJRdIju7Ac9teLYODgx3M8j5PlwFRW9gpvvQJ88y5BZCW-tc7Ud0mJrcutMb7CVHtyRek9FVM2acomJeFji2h6wYaGQ5hC8-mWxMJRyEG1sxoJjUe8N0G3nDXDbvBlLi4GX0cpx-Ie1jxIt7jfnKoelViCqvdazv04PhghHCqOEDeXG68XlxoY45nY2aKZd~qyT5zAP98AgT-nxYMzIVtORNaH3UxVFAF32Bc~fpcRk8FkheFehe9hSyBV8rEBPysg__"
          },
          {
            name: "Bryan",
            role: "Co Founder",
            image:
              "https://s3-alpha-sig.figma.com/img/51a2/6677/88ebcdbeeab9f107b69a80d1053e1aa1?Expires=1745193600&Key-Pair-Id=APKAQ4GOSFWCW27IBOMQ&Signature=nZgDTj9r9EJOqwOdteIogFbRnfPps9qzj63642UCBB7OyEexD585cAqh-R7ZkyRkxqKCoDJx2BYh3-rqougZe0FjFWtWXPbEV7usjJXGox1YbvoXlMBWXbb4RMk6lWnQux1VDxgrAIXvkr7Uuw4Rbee1wwGlkel89eLNOmePafMPIf5waCKHAlBDygchtYFFAk57ICg~o~leq-97YNz2tUsOgYoAESlD7fIOiVFoPzrJEbkG9KRYt~4laQ88xSRnWCU7bSnAxu468Riptg35Zs-kY1XNC671eFhD01ilEvzWi1-rmt2Biwcn7iiJlISyLfsgyDpAf~F~Av3c8d07bw__"
          },
          {
            name: "Emily",
            role: "Artist",
            image:
              "https://s3-alpha-sig.figma.com/img/b551/caf1/a50da17c794f41c2b771e5502c81c73e?Expires=1745193600&Key-Pair-Id=APKAQ4GOSFWCW27IBOMQ&Signature=GsoKh7MpJqm2TJDByvMOwq8hI9WuXVJg5-9fmELiq~HpexPjVmAOwxZKvJbKG5vEx6dzq5p5tfeMXluTXtolvOhBUGIzaHS2agzOROw0EHNwLmPLLg26HLnT70TOK4g6Iejv-nn0cA5jfLZMsiXzecohVjpUTfcDG9PLSg4gaHF4PNu~VwxdSAb5OuZETkp8JIRzQUeNFin2AJQeNwYw~CSEDbCzMVsXfjESv4zKxXOXkJL5d35l4WzdBRkskLgzKenvCu8CxlKwMHv6xCTY3aZwbcKtk45qy8r7DubMr5CL4g3NOIDZEsWLugGfyParilJxJMx7WB-1e1zFvtVpUw__"
          }
        ]
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantszDoh8C8VtaK()
  });

  return (
    <React.Fragment>
      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_antd_5_css.plasmic_tokens,
            sty.root
          )}
        >
          <div className={classNames(projectcss.all, sty.freeBox__rA5GP)}>
            <Header
              className={classNames("__wab_instance", sty.header__x4340)}
            />

            <div className={classNames(projectcss.all, sty.freeBox__q0Va)}>
              <div className={classNames(projectcss.all, sty.freeBox__c9Bom)}>
                <div className={classNames(projectcss.all, sty.freeBox__trPjh)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__gXtNr
                    )}
                  >
                    {"Magic Astronauts"}
                  </div>
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__xrJaw)}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img___0ErSa)}
                      displayHeight={"auto"}
                      displayMaxHeight={
                        hasVariant(globalVariants, "screen", "tabletSmall")
                          ? "550px"
                          : "400px"
                      }
                      displayMaxWidth={
                        hasVariant(globalVariants, "screen", "tabletSmall")
                          ? "none"
                          : "500px"
                      }
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={
                        hasVariant(globalVariants, "screen", "tablet")
                          ? "100%"
                          : "auto"
                      }
                      height={
                        hasVariant(globalVariants, "screen", "tabletSmall")
                          ? ``
                          : "400px"
                      }
                      loading={"lazy"}
                      src={
                        "https://s3-alpha-sig.figma.com/img/a629/5552/6c3db1cb6cee1f3f378041393aa1174e?Expires=1744588800&Key-Pair-Id=APKAQ4GOSFWCW27IBOMQ&Signature=NPr3LmBKbRkah9gVa2DR~gGmpttBKuNBgV9BH20s4FjwxF6eOjn8xx2BetsEoTUmfOslD0EKPF8k18z116~KCgIl3LelHyjP3kR2XEiupSVVjD6usq-qGtQ63L44v1Y3ollCwa5TGAkyobyPGVmdjuSKBh4ioR5Hw8G-mTaM61xtk46IBP2rYPTXyEZL3mAtUdoz1SqnAg-QcIHlMSG1WWMep7TkOmiJrxtQk8kS~HlL1zTu8HItzwrt9iDWMJtZf1Ea3PBkAPIcD0zJF9i2a0CGdQEDssQ6tflDd4ersUSSnwG05kKSDu3n3X04ar-FxMqEtbiLx47vajoJhKWs3A__"
                      }
                      width={
                        hasVariant(globalVariants, "screen", "tablet")
                          ? ``
                          : "500px"
                      }
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        sty.freeBox___1GysB
                      )}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__fvJuj
                        )}
                      >
                        {"Magic Astronauts"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__nCgo9
                        )}
                      >
                        {"Exclusive minting for whitelisted members"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__jiujJ
                        )}
                      >
                        {"ENDS IN"}
                      </div>
                      <Stack__
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__fgZ9Q
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__v0Il
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__auymb
                            )}
                          >
                            {"01"}
                          </div>
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__nnkZ
                            )}
                          >
                            {"day"}
                          </div>
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__hjHjs
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text___9OaQc
                            )}
                          >
                            {"10"}
                          </div>
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__ssFxf
                            )}
                          >
                            {"hour"}
                          </div>
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__qwM3R
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__cn9Tw
                            )}
                          >
                            {"10"}
                          </div>
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__dQFuG
                            )}
                          >
                            {"minute"}
                          </div>
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__ryztq
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__xUaNa
                            )}
                          >
                            {"30"}
                          </div>
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__gLXo
                            )}
                          >
                            {"second"}
                          </div>
                        </div>
                      </Stack__>
                      <ConnectWalletButton
                        data-plasmic-name={"connectWalletButton"}
                        data-plasmic-override={overrides.connectWalletButton}
                        className={classNames(
                          "__wab_instance",
                          sty.connectWalletButton
                        )}
                        connectText={"Connect Wallet"}
                      />
                    </div>
                  </Stack__>
                  <Tabs
                    data-plasmic-name={"antdTabs"}
                    data-plasmic-override={overrides.antdTabs}
                    activeKey={generateStateValueProp($state, [
                      "antdTabs",
                      "activeKey"
                    ])}
                    className={classNames("__wab_instance", sty.antdTabs)}
                    onChange={async (...eventArgs: any) => {
                      generateStateOnChangeProp($state, [
                        "antdTabs",
                        "activeKey"
                      ]).apply(null, eventArgs);
                    }}
                  >
                    <TabPane
                      className={classNames(
                        "__wab_instance",
                        sty.antdTabPane__hlctc
                      )}
                      key={"1"}
                      tab={
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__gzeg6
                          )}
                        >
                          {"Overview"}
                        </div>
                      }
                    >
                      <Stack__
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__cxsS
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__i2Spp
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__e4Nxb
                            )}
                          >
                            {"Magic Astronauts"}
                          </div>
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__o8IDa
                            )}
                          >
                            {
                              "Embark on a Cosmic Journey with Magic Astronauts! \ud83d\ude80\u2728\nWelcome to the Magic Astronauts NFT collection\u2014a mesmerizing fusion of space exploration and ethereal wonder! Each Magic Astronaut is a unique digital masterpiece, blending futuristic space gear with mystical elements that capture the boundless imagination of the cosmos."
                            }
                          </div>
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__kxzTy
                            )}
                          >
                            {"Collection Highlights"}
                          </div>
                          <ul
                            className={classNames(
                              projectcss.all,
                              projectcss.ul,
                              sty.ul___8YPmc
                            )}
                          >
                            <li
                              className={classNames(
                                projectcss.all,
                                projectcss.li,
                                sty.li__m9W6T
                              )}
                            >
                              <div
                                className={classNames(
                                  projectcss.all,
                                  sty.freeBox__nNd1Q
                                )}
                              >
                                <div
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.__wab_text,
                                    sty.text__qOmBa
                                  )}
                                >
                                  {
                                    "Unique Artworks: 1,000 one-of-a-kind NFTs, each featuring a Magic Astronaut with distinct traits, suits, and cosmic backgrounds."
                                  }
                                </div>
                              </div>
                            </li>
                          </ul>
                          <ul
                            className={classNames(
                              projectcss.all,
                              projectcss.ul,
                              sty.ul__pRrVi
                            )}
                          >
                            <li
                              className={classNames(
                                projectcss.all,
                                projectcss.li,
                                sty.li__b4EbR
                              )}
                            >
                              <div
                                className={classNames(
                                  projectcss.all,
                                  sty.freeBox__sBp73
                                )}
                              >
                                <div
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.__wab_text,
                                    sty.text__v2WDg
                                  )}
                                >
                                  {
                                    "Surreal Aesthetics: Inspired by the intersection of science fiction and fantasy, our astronauts float through enchanted cloudscapes, glowing nebulae, and starry voids."
                                  }
                                </div>
                              </div>
                            </li>
                          </ul>
                          <ul
                            className={classNames(
                              projectcss.all,
                              projectcss.ul,
                              sty.ul__blpxK
                            )}
                          >
                            <li
                              className={classNames(
                                projectcss.all,
                                projectcss.li,
                                sty.li__ud7Os
                              )}
                            >
                              <div
                                className={classNames(
                                  projectcss.all,
                                  sty.freeBox___9Jtlj
                                )}
                              >
                                <div
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.__wab_text,
                                    sty.text__aJfY
                                  )}
                                >
                                  {
                                    "Utility & Perks: Holders gain access to exclusive virtual space expeditions, community events, and future airdrops in the Magic Astronauts universe."
                                  }
                                </div>
                              </div>
                            </li>
                          </ul>
                        </div>
                        <AntdSteps
                          data-plasmic-name={"steps"}
                          data-plasmic-override={overrides.steps}
                          className={classNames("__wab_instance", sty.steps)}
                          current={generateStateValueProp($state, [
                            "steps",
                            "current"
                          ])}
                          direction={"vertical"}
                          items={(() => {
                            const __composite = [
                              { title: null, description: null },
                              { title: null, description: null },
                              { title: null, description: null, disabled: null }
                            ];
                            __composite["0"]["title"] = "March 20, 2025";
                            __composite["0"]["description"] =
                              "Early access and exclusive benefits for early supporters";
                            __composite["1"]["title"] = "April 20, 2025";
                            __composite["1"]["description"] =
                              "Priority minting for whitelisted members";
                            __composite["2"]["title"] = "May 20, 2025";
                            __composite["2"]["description"] =
                              "Open minting for everyone";
                            __composite["2"]["disabled"] = false;
                            return __composite;
                          })()}
                          onChange={async (...eventArgs: any) => {
                            generateStateOnChangeProp($state, [
                              "steps",
                              "current"
                            ]).apply(null, eventArgs);
                          }}
                          progressDot={false}
                          responsive={true}
                          size={"small"}
                        />
                      </Stack__>
                    </TabPane>
                    <TabPane
                      className={classNames(
                        "__wab_instance",
                        sty.antdTabPane__fPpc4
                      )}
                      key={"2"}
                      tab={
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text___7H0Dp
                          )}
                        >
                          {"Team"}
                        </div>
                      }
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__dVw6U
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__vl9Ve
                          )}
                        >
                          {(_par =>
                            !_par ? [] : Array.isArray(_par) ? _par : [_par])(
                            []
                          ).map((__plasmic_item_0, __plasmic_idx_0) => {
                            const currentItem = __plasmic_item_0;
                            const currentIndex = __plasmic_idx_0;
                            return (
                              <div
                                className={classNames(
                                  projectcss.all,
                                  sty.freeBox__q7Wo
                                )}
                                key={currentIndex}
                              >
                                <PlasmicImg__
                                  alt={""}
                                  className={classNames(sty.img__ovZBl)}
                                  displayHeight={"auto"}
                                  displayMaxHeight={"200px"}
                                  displayMaxWidth={"none"}
                                  displayMinHeight={"0"}
                                  displayMinWidth={"0"}
                                  displayWidth={"auto"}
                                  loading={"lazy"}
                                  src={(() => {
                                    try {
                                      return currentItem.img;
                                    } catch (e) {
                                      if (e instanceof TypeError) {
                                        return "https://s3-alpha-sig.figma.com/img/d125/0dcf/43d2a28cf3971315cbc5d8f588f7d3da?Expires=1744588800&Key-Pair-Id=APKAQ4GOSFWCW27IBOMQ&Signature=QCo3rE7lOrN-ynf84KzwxQQi1552o2sj0e-Zkm1u-lqkuVjKB10BiogIbM~tOfyfZqWkpW7c5pM2dBBGIRlg1Qyy~iJ5~9EHfgREFixlns62HXLXaLHFJRTXth2ZEuFJm5sZ0uTdrvmv8cW0oTtZFGpZ2AEy7cPYD8gsMxKXyboiNLVXO301QHK5TPmnVdKrx5kGEqtGvud6OPtqd5Tu19Omt5FqvrW-ZF2WtP2ELeymdquEQ~z9JnGcUy1ZbpYF86djav6ceaTIYpNhuBRJ5Gqp10NSRfbz~AEwfaPPyag2YQrtX9UMu3payh~uHTfm~u8i0YG5T7LLD9ZnmxWdow__";
                                      }
                                      throw e;
                                    }
                                  })()}
                                />

                                <div
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.__wab_text,
                                    sty.text__cNpi0
                                  )}
                                >
                                  <React.Fragment>
                                    {(() => {
                                      try {
                                        return currentItem.name;
                                      } catch (e) {
                                        if (e instanceof TypeError) {
                                          return "Magic Astronaut #001 ";
                                        }
                                        throw e;
                                      }
                                    })()}
                                  </React.Fragment>
                                </div>
                                <div
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.__wab_text,
                                    sty.text__fvxrr
                                  )}
                                >
                                  <React.Fragment>
                                    {(() => {
                                      try {
                                        return currentItem.price;
                                      } catch (e) {
                                        if (e instanceof TypeError) {
                                          return "5.67 SUI";
                                        }
                                        throw e;
                                      }
                                    })()}
                                  </React.Fragment>
                                </div>
                              </div>
                            );
                          })}
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__oBs1V
                          )}
                        >
                          {(_par =>
                            !_par ? [] : Array.isArray(_par) ? _par : [_par])(
                            []
                          ).map((__plasmic_item_0, __plasmic_idx_0) => {
                            const currentItem = __plasmic_item_0;
                            const currentIndex = __plasmic_idx_0;
                            return (
                              <div
                                className={classNames(
                                  projectcss.all,
                                  sty.freeBox__yGydb
                                )}
                                key={currentIndex}
                              >
                                <PlasmicImg__
                                  alt={""}
                                  className={classNames(sty.img__viHsh)}
                                  displayHeight={"auto"}
                                  displayMaxHeight={"200px"}
                                  displayMaxWidth={"none"}
                                  displayMinHeight={"0"}
                                  displayMinWidth={"0"}
                                  displayWidth={"auto"}
                                  loading={"lazy"}
                                  src={(() => {
                                    try {
                                      return currentItem.img;
                                    } catch (e) {
                                      if (e instanceof TypeError) {
                                        return "https://s3-alpha-sig.figma.com/img/d125/0dcf/43d2a28cf3971315cbc5d8f588f7d3da?Expires=1744588800&Key-Pair-Id=APKAQ4GOSFWCW27IBOMQ&Signature=QCo3rE7lOrN-ynf84KzwxQQi1552o2sj0e-Zkm1u-lqkuVjKB10BiogIbM~tOfyfZqWkpW7c5pM2dBBGIRlg1Qyy~iJ5~9EHfgREFixlns62HXLXaLHFJRTXth2ZEuFJm5sZ0uTdrvmv8cW0oTtZFGpZ2AEy7cPYD8gsMxKXyboiNLVXO301QHK5TPmnVdKrx5kGEqtGvud6OPtqd5Tu19Omt5FqvrW-ZF2WtP2ELeymdquEQ~z9JnGcUy1ZbpYF86djav6ceaTIYpNhuBRJ5Gqp10NSRfbz~AEwfaPPyag2YQrtX9UMu3payh~uHTfm~u8i0YG5T7LLD9ZnmxWdow__";
                                      }
                                      throw e;
                                    }
                                  })()}
                                />

                                <div
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.__wab_text,
                                    sty.text__oyOb
                                  )}
                                >
                                  <React.Fragment>
                                    {(() => {
                                      try {
                                        return currentItem.name;
                                      } catch (e) {
                                        if (e instanceof TypeError) {
                                          return "Magic Astronaut #001 ";
                                        }
                                        throw e;
                                      }
                                    })()}
                                  </React.Fragment>
                                </div>
                                <div
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.__wab_text,
                                    sty.text__aHj1L
                                  )}
                                >
                                  <React.Fragment>
                                    {(() => {
                                      try {
                                        return currentItem.price;
                                      } catch (e) {
                                        if (e instanceof TypeError) {
                                          return "5.67 SUI";
                                        }
                                        throw e;
                                      }
                                    })()}
                                  </React.Fragment>
                                </div>
                              </div>
                            );
                          })}
                        </div>
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox___4FjsC
                        )}
                      >
                        {(_par =>
                          !_par ? [] : Array.isArray(_par) ? _par : [_par])(
                          (() => {
                            try {
                              return $state.teamMembers;
                            } catch (e) {
                              if (e instanceof TypeError) {
                                return [];
                              }
                              throw e;
                            }
                          })()
                        ).map((__plasmic_item_0, __plasmic_idx_0) => {
                          const currentItem = __plasmic_item_0;
                          const currentIndex = __plasmic_idx_0;
                          return (
                            <div
                              className={classNames(
                                projectcss.all,
                                sty.freeBox__qMhOp
                              )}
                              key={currentIndex}
                            >
                              <PlasmicImg__
                                alt={""}
                                className={classNames(sty.img__dg3Oe)}
                                displayHeight={
                                  hasVariant(
                                    globalVariants,
                                    "screen",
                                    "mobileSmall"
                                  )
                                    ? "350px"
                                    : hasVariant(
                                        globalVariants,
                                        "screen",
                                        "mobileLarge"
                                      )
                                    ? "280px"
                                    : hasVariant(
                                        globalVariants,
                                        "screen",
                                        "tabletSmall"
                                      )
                                    ? "260px"
                                    : "160px"
                                }
                                displayMaxHeight={
                                  hasVariant(
                                    globalVariants,
                                    "screen",
                                    "tabletSmall"
                                  )
                                    ? "none"
                                    : "160px"
                                }
                                displayMaxWidth={"100%"}
                                displayMinHeight={"0"}
                                displayMinWidth={"0"}
                                displayWidth={"auto"}
                                loading={"lazy"}
                                src={(() => {
                                  try {
                                    return currentItem.image;
                                  } catch (e) {
                                    if (e instanceof TypeError) {
                                      return "https://s3-alpha-sig.figma.com/img/21c1/c284/eddacccb4e22ee7d2abea1058a784bf2?Expires=1745193600&Key-Pair-Id=APKAQ4GOSFWCW27IBOMQ&Signature=gCneODEcNL1rKq3gWwUkRGlMlkJiFOW-TSt3US569UZ3P2lun0RdhKinihk9KoYX7OFOXMaHGpH-NcFt6CbRZJRdIju7Ac9teLYODgx3M8j5PlwFRW9gpvvQJ88y5BZCW-tc7Ud0mJrcutMb7CVHtyRek9FVM2acomJeFji2h6wYaGQ5hC8-mWxMJRyEG1sxoJjUe8N0G3nDXDbvBlLi4GX0cpx-Ie1jxIt7jfnKoelViCqvdazv04PhghHCqOEDeXG68XlxoY45nY2aKZd~qyT5zAP98AgT-nxYMzIVtORNaH3UxVFAF32Bc~fpcRk8FkheFehe9hSyBV8rEBPysg__";
                                    }
                                    throw e;
                                  }
                                })()}
                              />

                              <div
                                className={classNames(
                                  projectcss.all,
                                  sty.freeBox__kqe3F
                                )}
                              >
                                <div
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.__wab_text,
                                    sty.text__b0H4U
                                  )}
                                >
                                  <React.Fragment>
                                    {(() => {
                                      try {
                                        return currentItem.name;
                                      } catch (e) {
                                        if (e instanceof TypeError) {
                                          return "James";
                                        }
                                        throw e;
                                      }
                                    })()}
                                  </React.Fragment>
                                </div>
                                <div
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.__wab_text,
                                    sty.text__zzNsA
                                  )}
                                >
                                  <React.Fragment>
                                    {(() => {
                                      try {
                                        return currentItem.role;
                                      } catch (e) {
                                        if (e instanceof TypeError) {
                                          return "Co Founder";
                                        }
                                        throw e;
                                      }
                                    })()}
                                  </React.Fragment>
                                </div>
                              </div>
                            </div>
                          );
                        })}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__nouHw
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__h9F02
                          )}
                        />
                      </div>
                    </TabPane>
                  </Tabs>
                </div>
              </div>
            </div>
            {false ? (
              <div className={classNames(projectcss.all, sty.freeBox__upyml)}>
                <Header
                  className={classNames("__wab_instance", sty.header__iuyNa)}
                />

                <div className={classNames(projectcss.all, sty.freeBox__quN5Z)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__jUoyh)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__w77R)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__fph00
                        )}
                      >
                        {"Magic Astronauts"}
                      </div>
                      <Stack__
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__vEv5D
                        )}
                      >
                        <PlasmicImg__
                          alt={""}
                          className={classNames(sty.img__jk59P)}
                          displayHeight={"auto"}
                          displayMaxHeight={"400px"}
                          displayMaxWidth={"500px"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"auto"}
                          height={"400px"}
                          loading={"lazy"}
                          src={
                            "https://s3-alpha-sig.figma.com/img/a629/5552/6c3db1cb6cee1f3f378041393aa1174e?Expires=1744588800&Key-Pair-Id=APKAQ4GOSFWCW27IBOMQ&Signature=NPr3LmBKbRkah9gVa2DR~gGmpttBKuNBgV9BH20s4FjwxF6eOjn8xx2BetsEoTUmfOslD0EKPF8k18z116~KCgIl3LelHyjP3kR2XEiupSVVjD6usq-qGtQ63L44v1Y3ollCwa5TGAkyobyPGVmdjuSKBh4ioR5Hw8G-mTaM61xtk46IBP2rYPTXyEZL3mAtUdoz1SqnAg-QcIHlMSG1WWMep7TkOmiJrxtQk8kS~HlL1zTu8HItzwrt9iDWMJtZf1Ea3PBkAPIcD0zJF9i2a0CGdQEDssQ6tflDd4ersUSSnwG05kKSDu3n3X04ar-FxMqEtbiLx47vajoJhKWs3A__"
                          }
                          width={"500px"}
                        />

                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__ts63U
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__szPpf
                            )}
                          >
                            {"Magic Astronauts"}
                          </div>
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__bv1Gt
                            )}
                          >
                            {"Exclusive minting for whitelisted members"}
                          </div>
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__xfKt6
                            )}
                          >
                            {"ENDS IN"}
                          </div>
                          <Stack__
                            as={"div"}
                            hasGap={true}
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__rtOZz
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                sty.freeBox__xI3J1
                              )}
                            >
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text___9S273
                                )}
                              >
                                {"01"}
                              </div>
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text__xdV9L
                                )}
                              >
                                {"day"}
                              </div>
                            </div>
                            <div
                              className={classNames(
                                projectcss.all,
                                sty.freeBox___7FJgL
                              )}
                            >
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text__fkcYu
                                )}
                              >
                                {"10"}
                              </div>
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text___9Cin
                                )}
                              >
                                {"hour"}
                              </div>
                            </div>
                            <div
                              className={classNames(
                                projectcss.all,
                                sty.freeBox__dX3
                              )}
                            >
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text__tFh13
                                )}
                              >
                                {"10"}
                              </div>
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text__kzejQ
                                )}
                              >
                                {"minute"}
                              </div>
                            </div>
                            <div
                              className={classNames(
                                projectcss.all,
                                sty.freeBox__dEqrA
                              )}
                            >
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text__cnVzX
                                )}
                              >
                                {"30"}
                              </div>
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text__zdGVt
                                )}
                              >
                                {"second"}
                              </div>
                            </div>
                          </Stack__>
                        </div>
                      </Stack__>
                      <Tabs
                        data-plasmic-name={"antdTabs2"}
                        data-plasmic-override={overrides.antdTabs2}
                        activeKey={generateStateValueProp($state, [
                          "antdTabs2",
                          "activeKey"
                        ])}
                        className={classNames("__wab_instance", sty.antdTabs2)}
                        onChange={async (...eventArgs: any) => {
                          generateStateOnChangeProp($state, [
                            "antdTabs2",
                            "activeKey"
                          ]).apply(null, eventArgs);
                        }}
                      >
                        <TabPane
                          className={classNames(
                            "__wab_instance",
                            sty.antdTabPane__cSmHu
                          )}
                          key={"1"}
                          tab={
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__wvS2Z
                              )}
                            >
                              {"Overview"}
                            </div>
                          }
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__uTml
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                sty.freeBox__e8Gc1
                              )}
                            >
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text__n6HIc
                                )}
                              >
                                {"Magic Astronauts"}
                              </div>
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text__bkNv
                                )}
                              >
                                {
                                  "Embark on a Cosmic Journey with Magic Astronauts! \ud83d\ude80\u2728\nWelcome to the Magic Astronauts NFT collection\u2014a mesmerizing fusion of space exploration and ethereal wonder! Each Magic Astronaut is a unique digital masterpiece, blending futuristic space gear with mystical elements that capture the boundless imagination of the cosmos."
                                }
                              </div>
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text__wiZZ
                                )}
                              >
                                {"Collection Highlights"}
                              </div>
                              <ul
                                className={classNames(
                                  projectcss.all,
                                  projectcss.ul,
                                  sty.ul__t0YbY
                                )}
                              >
                                <li
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.li,
                                    sty.li__kqm8N
                                  )}
                                >
                                  <div
                                    className={classNames(
                                      projectcss.all,
                                      sty.freeBox__uKl3H
                                    )}
                                  >
                                    <div
                                      className={classNames(
                                        projectcss.all,
                                        projectcss.__wab_text,
                                        sty.text___844Xl
                                      )}
                                    >
                                      {
                                        "Unique Artworks: 1,000 one-of-a-kind NFTs, each featuring a Magic Astronaut with distinct traits, suits, and cosmic backgrounds."
                                      }
                                    </div>
                                  </div>
                                </li>
                              </ul>
                              <ul
                                className={classNames(
                                  projectcss.all,
                                  projectcss.ul,
                                  sty.ul__pczz2
                                )}
                              >
                                <li
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.li,
                                    sty.li__zuBbx
                                  )}
                                >
                                  <div
                                    className={classNames(
                                      projectcss.all,
                                      sty.freeBox__kcrZt
                                    )}
                                  >
                                    <div
                                      className={classNames(
                                        projectcss.all,
                                        projectcss.__wab_text,
                                        sty.text__kuKKy
                                      )}
                                    >
                                      {
                                        "Surreal Aesthetics: Inspired by the intersection of science fiction and fantasy, our astronauts float through enchanted cloudscapes, glowing nebulae, and starry voids."
                                      }
                                    </div>
                                  </div>
                                </li>
                              </ul>
                              <ul
                                className={classNames(
                                  projectcss.all,
                                  projectcss.ul,
                                  sty.ul__bXqJj
                                )}
                              >
                                <li
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.li,
                                    sty.li__qhOt
                                  )}
                                >
                                  <div
                                    className={classNames(
                                      projectcss.all,
                                      sty.freeBox__oKKko
                                    )}
                                  >
                                    <div
                                      className={classNames(
                                        projectcss.all,
                                        projectcss.__wab_text,
                                        sty.text__jegcV
                                      )}
                                    >
                                      {
                                        "Utility & Perks: Holders gain access to exclusive virtual space expeditions, community events, and future airdrops in the Magic Astronauts universe."
                                      }
                                    </div>
                                  </div>
                                </li>
                              </ul>
                            </div>
                            <AntdSteps
                              data-plasmic-name={"steps2"}
                              data-plasmic-override={overrides.steps2}
                              className={classNames(
                                "__wab_instance",
                                sty.steps2
                              )}
                              current={generateStateValueProp($state, [
                                "steps2",
                                "current"
                              ])}
                              direction={"vertical"}
                              items={(() => {
                                const __composite = [
                                  { title: null, description: null },
                                  { title: null, description: null },
                                  {
                                    title: null,
                                    description: null,
                                    disabled: null
                                  }
                                ];
                                __composite["0"]["title"] = "March 20, 2025";
                                __composite["0"]["description"] =
                                  "Early access and exclusive benefits for early supporters";
                                __composite["1"]["title"] = "April 20, 2025";
                                __composite["1"]["description"] =
                                  "Priority minting for whitelisted members";
                                __composite["2"]["title"] = "May 20, 2025";
                                __composite["2"]["description"] =
                                  "Open minting for everyone";
                                __composite["2"]["disabled"] = false;
                                return __composite;
                              })()}
                              onChange={async (...eventArgs: any) => {
                                generateStateOnChangeProp($state, [
                                  "steps2",
                                  "current"
                                ]).apply(null, eventArgs);
                              }}
                              progressDot={false}
                              responsive={true}
                              size={"small"}
                            />
                          </div>
                        </TabPane>
                        <TabPane
                          className={classNames(
                            "__wab_instance",
                            sty.antdTabPane__m8Cgw
                          )}
                          key={"2"}
                          tab={
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text___64KOq
                              )}
                            >
                              {"Team"}
                            </div>
                          }
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__lJtSl
                            )}
                          >
                            {"Tab content"}
                          </div>
                        </TabPane>
                      </Tabs>
                    </div>
                  </div>
                </div>
              </div>
            ) : null}
          </div>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "connectWalletButton",
    "antdTabs",
    "steps",
    "antdTabs2",
    "steps2"
  ],
  connectWalletButton: ["connectWalletButton"],
  antdTabs: ["antdTabs", "steps"],
  steps: ["steps"],
  antdTabs2: ["antdTabs2", "steps2"],
  steps2: ["steps2"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  connectWalletButton: typeof ConnectWalletButton;
  antdTabs: typeof Tabs;
  steps: typeof AntdSteps;
  antdTabs2: typeof Tabs;
  steps2: typeof AntdSteps;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicConnectWalletViewMintingNftDetails__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicConnectWalletViewMintingNftDetails__VariantsArgs;
    args?: PlasmicConnectWalletViewMintingNftDetails__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit< // Specify variants directly as props
    PlasmicConnectWalletViewMintingNftDetails__VariantsArgs,
    ReservedPropsType
  > &
    // Specify args directly as props
    Omit<
      PlasmicConnectWalletViewMintingNftDetails__ArgsType,
      ReservedPropsType
    > &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames:
            PlasmicConnectWalletViewMintingNftDetails__ArgProps,
          internalVariantPropNames:
            PlasmicConnectWalletViewMintingNftDetails__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicConnectWalletViewMintingNftDetails__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicConnectWalletViewMintingNftDetails";
  } else {
    func.displayName = `PlasmicConnectWalletViewMintingNftDetails.${nodeName}`;
  }
  return func;
}

export const PlasmicConnectWalletViewMintingNftDetails = Object.assign(
  // Top-level PlasmicConnectWalletViewMintingNftDetails renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    connectWalletButton: makeNodeComponent("connectWalletButton"),
    antdTabs: makeNodeComponent("antdTabs"),
    steps: makeNodeComponent("steps"),
    antdTabs2: makeNodeComponent("antdTabs2"),
    steps2: makeNodeComponent("steps2"),

    // Metadata about props expected for PlasmicConnectWalletViewMintingNftDetails
    internalVariantProps:
      PlasmicConnectWalletViewMintingNftDetails__VariantProps,
    internalArgProps: PlasmicConnectWalletViewMintingNftDetails__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicConnectWalletViewMintingNftDetails;
/* prettier-ignore-end */
